export const Paths = {
    index: '/',
    ajoonamu: {
        signin: '/login',
        signup: '/register',
        recovery: '/recovery',
        recovery_id: '/recovery_id',
        recovery_pw: '/recovery_pw',
        complete: '/complete',
        find_email :'/find_email',
        find_password : '/find_password',
        shop: '/shop',
        mypage: '/mypage',
        account: '/account',
        update_name: '/update_name',
        update_phone: '/update_phone',
        update_password: '/update_password',
        address: '/address',
        cart: '/cart',
        order: '/order',
        order_list: '/order_list',
        order_detail:'/order_detail',
        order_complete :'/order_complete',
        coupon: '/coupon',
        support: '/support',
        notice: '/notice',
        event: '/event'
    },
    api: 'http://devapi.ajoonamu.com/api/',
};
